# Generated by Django 5.2.10 on 2026-02-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Unique Visitors')),
                ('total_page_views', models.PositiveIntegerField(default=0, verbose_name='Total Page Views')),
                ('leads_count', models.PositiveIntegerField(default=0, verbose_name='Leads Count')),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='First Visit')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Last Visit')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='Visit Count')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='Page Path')),
                ('referer', models.URLField(blank=True, default='', verbose_name='Referer')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor', verbose_name='Visitor')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-timestamp'],
            },
        ),
    ]
