# Generated by Django 5.2.10 on 2026-01-29 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(blank=True, default='', max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='amenities/')),
            ],
            options={
                'verbose_name': 'Qulaylik',
                'verbose_name_plural': 'Qulayliklar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(blank=True, default='', max_length=255)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail_image', models.ImageField(upload_to='projects/thumbnails/')),
                ('completion_date', models.DateField()),
                ('location_name', models.CharField(max_length=255)),
                ('location_name_uz', models.CharField(blank=True, default='', max_length=255)),
                ('location_name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('location_name_en', models.CharField(blank=True, default='', max_length=255)),
                ('total_houses', models.PositiveIntegerField(default=0)),
                ('segment', models.CharField(choices=[('business', 'Buisnes'), ('comfort', 'Comfort'), ('premium', 'Premium')], default='business', max_length=32)),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_year', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.PositiveIntegerField()),
                ('floor', models.IntegerField()),
                ('number', models.CharField(max_length=64)),
                ('image', models.ImageField(upload_to='apartments/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='content.project')),
            ],
            options={
                'verbose_name': 'Xonadon',
                'verbose_name_plural': 'Xonadonlar',
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(upload_to='projects/details/header/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='projects/details/header/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='projects/details/header/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='projects/details/header/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='projects/details/header/')),
                ('about_description', models.TextField()),
                ('about_description_uz', models.TextField(blank=True, default='')),
                ('about_description_ru', models.TextField(blank=True, default='')),
                ('about_description_en', models.TextField(blank=True, default='')),
                ('about_image', models.ImageField(upload_to='projects/details/about/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('architecture_description', models.TextField()),
                ('architecture_description_uz', models.TextField(blank=True, default='')),
                ('architecture_description_ru', models.TextField(blank=True, default='')),
                ('architecture_description_en', models.TextField(blank=True, default='')),
                ('architecture_image1', models.ImageField(upload_to='projects/details/architecture/')),
                ('architecture_image2', models.ImageField(upload_to='projects/details/architecture/')),
                ('architecture_image3', models.ImageField(upload_to='projects/details/architecture/')),
                ('interior_description', models.TextField()),
                ('interior_description_uz', models.TextField(blank=True, default='')),
                ('interior_description_ru', models.TextField(blank=True, default='')),
                ('interior_description_en', models.TextField(blank=True, default='')),
                ('interior_image', models.ImageField(upload_to='projects/details/interior/')),
                ('amenities', models.ManyToManyField(blank=True, to='content.amenity', verbose_name='Premium Amenities')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='content.project')),
            ],
            options={
                'verbose_name': 'Loyiha tafsiloti',
                'verbose_name_plural': 'Loyiha tafsilotlari',
            },
        ),
    ]
