# Generated by Django 5.2.10 on 2026-01-28 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(blank=True, default='', max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='amenities/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('under_construction', 'Under Construction'), ('for_sale', 'For Sale'), ('completed', 'Completed')], default='for_sale', max_length=32)),
                ('project_class', models.CharField(choices=[('comfort', 'Comfort'), ('business', 'Business'), ('premium', 'Premium')], default='business', max_length=32)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('blocks', models.PositiveIntegerField(default=0)),
                ('total_area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('floors', models.PositiveIntegerField(default=0)),
                ('map_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('map_embed_url', models.TextField(blank=True, default='')),
                ('short_description_uz', models.TextField(blank=True, default='')),
                ('short_description_ru', models.TextField(blank=True, default='')),
                ('short_description_en', models.TextField(blank=True, default='')),
                ('full_description_uz', models.TextField(blank=True, default='')),
                ('full_description_ru', models.TextField(blank=True, default='')),
                ('full_description_en', models.TextField(blank=True, default='')),
                ('architecture_description_uz', models.TextField(blank=True, default='')),
                ('architecture_description_ru', models.TextField(blank=True, default='')),
                ('architecture_description_en', models.TextField(blank=True, default='')),
                ('interior_description_uz', models.TextField(blank=True, default='')),
                ('interior_description_ru', models.TextField(blank=True, default='')),
                ('interior_description_en', models.TextField(blank=True, default='')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('amenities', models.ManyToManyField(blank=True, related_name='projects', to='content.amenity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=64)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('delivery_year', models.PositiveIntegerField(default=2026)),
                ('is_available', models.BooleanField(default=True)),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='apartments/floor-plans/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='content.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('kind', models.CharField(choices=[('architecture', 'Architecture'), ('gallery', 'Gallery')], default='gallery', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
