# Generated by Django 5.2.10 on 2026-01-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_houses',
            new_name='number_of_houses',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location_name_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location_name_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location_name_uz',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='', upload_to='projects/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('completed', 'Completed'), ('for_sale', 'For Sale'), ('will_start', 'Will Start')], default='under_construction', max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='segment',
            field=models.CharField(choices=[('premium', 'Premium'), ('business', 'Business'), ('comfort', 'Comfort')], default='business', max_length=32),
        ),
    ]
