# Generated by Django 5.2.10 on 2026-01-31 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_total_houses_project_number_of_houses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Amenity', 'verbose_name_plural': 'Amenities'},
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Apartment', 'verbose_name_plural': 'Apartments'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectdetail',
            options={'verbose_name': 'Project Detail', 'verbose_name_plural': 'Project Details'},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='amenities/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (Russian)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='delivery_year',
            field=models.PositiveIntegerField(verbose_name='Delivery Year'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(upload_to='apartments/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=64, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='content.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveIntegerField(verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number_of_houses',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Houses'),
        ),
        migrations.AlterField(
            model_name='project',
            name='segment',
            field=models.CharField(choices=[('premium', 'Premium'), ('business', 'Business'), ('comfort', 'Comfort')], default='business', max_length=32, verbose_name='Segment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('under_construction', 'Under Construction'), ('completed', 'Completed'), ('for_sale', 'For Sale'), ('will_start', 'Will Start')], default='under_construction', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='about_description',
            field=models.TextField(verbose_name='About Description'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='about_description_en',
            field=models.TextField(blank=True, default='', verbose_name='About Description (English)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='about_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='About Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='about_description_uz',
            field=models.TextField(blank=True, default='', verbose_name='About Description (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='about_image',
            field=models.ImageField(upload_to='projects/details/about/', verbose_name='About Image'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_description',
            field=models.TextField(verbose_name='Architecture Description'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Architecture Description (English)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Architecture Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_description_uz',
            field=models.TextField(blank=True, default='', verbose_name='Architecture Description (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_image1',
            field=models.ImageField(upload_to='projects/details/architecture/', verbose_name='Architecture Image 1'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_image2',
            field=models.ImageField(upload_to='projects/details/architecture/', verbose_name='Architecture Image 2'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_image3',
            field=models.ImageField(upload_to='projects/details/architecture/', verbose_name='Architecture Image 3'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image1',
            field=models.ImageField(upload_to='projects/details/header/', verbose_name='Header Image 1'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/header/', verbose_name='Header Image 2'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/header/', verbose_name='Header Image 3'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/header/', verbose_name='Header Image 4'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/header/', verbose_name='Header Image 5'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_description',
            field=models.TextField(verbose_name='Interior Description'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Interior Description (English)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Interior Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_description_uz',
            field=models.TextField(blank=True, default='', verbose_name='Interior Description (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_image',
            field=models.ImageField(upload_to='projects/details/interior/', verbose_name='Interior Image'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='content.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
