# Generated by Django 5.2.10 on 2026-02-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_amenity_options_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_description',
            field=models.TextField(blank=True, default='', verbose_name='Interior Description'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='interior_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/interior/', verbose_name='Interior Image'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='InteriorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name_uz', models.CharField(blank=True, default='', max_length=255, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Name (Russian)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Name (English)')),
                ('description_uz', models.TextField(blank=True, default='', verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Description (Russian)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (English)')),
                ('image', models.ImageField(upload_to='projects/details/interior/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_sections', to='content.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Interior Section',
                'verbose_name_plural': 'Interior Sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
