# Generated by Django 5.2.10 on 2026-02-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_interior_section_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Paste YouTube video link, e.g. https://www.youtube.com/watch?v=abc123', max_length=500, verbose_name='YouTube Video URL'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_description',
            field=models.TextField(blank=True, default='', verbose_name='Architecture Description'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_image1',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/architecture/', verbose_name='Architecture Image 1'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_image2',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/architecture/', verbose_name='Architecture Image 2'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='architecture_image3',
            field=models.ImageField(blank=True, null=True, upload_to='projects/details/architecture/', verbose_name='Architecture Image 3'),
        ),
        migrations.CreateModel(
            name='ArchitectureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title_uz', models.CharField(blank=True, default='', max_length=255, verbose_name='Title (Uzbek)')),
                ('title_ru', models.CharField(blank=True, default='', max_length=255, verbose_name='Title (Russian)')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Title (English)')),
                ('description_uz', models.TextField(blank=True, default='', verbose_name='Description (Uzbek)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Description (Russian)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Description (English)')),
                ('image', models.ImageField(upload_to='projects/details/architecture/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_sections', to='content.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Architecture Section',
                'verbose_name_plural': 'Architecture Sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
