# Generated by Django 5.2.10 on 2026-02-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_add_architecture_section_and_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Location Name (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Location Name (RU)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Location Name (UZ)'),
        ),
    ]
