# Generated by Django 5.2.10 on 2026-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, default='General Construction', max_length=255)),
                ('phone_primary', models.CharField(blank=True, default='', max_length=64)),
                ('phone_secondary', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_uz', models.TextField(blank=True, default='')),
                ('address_ru', models.TextField(blank=True, default='')),
                ('address_en', models.TextField(blank=True, default='')),
                ('office_hours_uz', models.TextField(blank=True, default='')),
                ('office_hours_ru', models.TextField(blank=True, default='')),
                ('office_hours_en', models.TextField(blank=True, default='')),
                ('map_embed_url', models.TextField(blank=True, default='')),
                ('telegram_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('footer_text_uz', models.TextField(blank=True, default='')),
                ('footer_text_ru', models.TextField(blank=True, default='')),
                ('footer_text_en', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
