# Generated by Django 5.2.10 on 2026-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, default='', verbose_name='Address (English)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.TextField(blank=True, default='', verbose_name='Address (Russian)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_uz',
            field=models.TextField(blank=True, default='', verbose_name='Address (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(blank=True, default='General Construction', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='', verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, default='', verbose_name='Footer Text (English)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Footer Text (Russian)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text_uz',
            field=models.TextField(blank=True, default='', verbose_name='Footer Text (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True, default='', verbose_name='Map Embed URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='office_hours_en',
            field=models.TextField(blank=True, default='', verbose_name='Office Hours (English)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='office_hours_ru',
            field=models.TextField(blank=True, default='', verbose_name='Office Hours (Russian)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='office_hours_uz',
            field=models.TextField(blank=True, default='', verbose_name='Office Hours (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Primary Phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_url',
            field=models.URLField(blank=True, default='', verbose_name='Telegram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, default='', verbose_name='YouTube URL'),
        ),
    ]
