# Generated by Django 5.2.10 on 2026-01-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('news', 'News'), ('promo', 'Promo')], default='news', max_length=16)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('title_uz', models.CharField(blank=True, default='', max_length=255)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('excerpt_uz', models.TextField(blank=True, default='')),
                ('excerpt_ru', models.TextField(blank=True, default='')),
                ('excerpt_en', models.TextField(blank=True, default='')),
                ('content_uz', models.TextField(blank=True, default='')),
                ('content_ru', models.TextField(blank=True, default='')),
                ('content_en', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
