# Generated by Django 5.2.10 on 2026-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
        migrations.AlterField(
            model_name='newspost',
            name='additional_information',
            field=models.TextField(blank=True, default='', verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='additional_information_en',
            field=models.TextField(blank=True, default='', verbose_name='Additional Information (English)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='additional_information_ru',
            field=models.TextField(blank=True, default='', verbose_name='Additional Information (Russian)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='additional_information_uz',
            field=models.TextField(blank=True, default='', verbose_name='Additional Information (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='date_of_creation',
            field=models.DateField(help_text='For showing in frontend', verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Description (Russian)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='description_uz',
            field=models.TextField(blank=True, default='', verbose_name='Description (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title (Russian)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='title_uz',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title (Uzbek)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
